### ISSUE TITLE
Topics introduced in Bot API 6.3

### ISSUE THREAD

**Issue by yurnov** [F1ashhimself/electricitybot#1]
Bot API 6.3 (released November 5, 2022) added support for [Topics in Groups](https://telegram.org/blog/topics-in-groups-collectible-usernames#topics-in-groups) that is not supported in bot. 

Therefore bot may not work for a group chat with topics.

**Comment by yurnov** [comment]
I'm going to prepare a PR for this issue. Currently commit prepared in https://github.com/yurnov/electricitybot/tree/topic

**Comment by yurnov** [comment]
Hi @F1ashhimself, please review PR #2 where Topics are introduced. I running a docker container with version (actually with  commit 2fc720bc8135649ba954d004a423a22952306ecf) for my "neighborhood chat" with Topics enabled (it was updated few hours ago from some previous version)

**Comment by F1ashhimself** [comment]
Closed with #3

**Comment by yurnov** [comment]
Hi @F1ashhimself, I see that test failed [here](https://github.com/F1ashhimself/electricitybot/actions/runs/3698799953/jobs/6265435425)
